### ISSUE TITLE
Auth0 issue when you don't use Google

### ISSUE THREAD

**Issue by GRamirez2** [josedigital/koala-app#17]
Tried to log in not using Google and it's not creating a user in the DB. Can't test delete user, unless someone logs using my machine. Maybe we can remove that option?

**Comment by josedigital** [comment]
yea, we'll have to remove it. creating a user (not using google auth) saves the user data in the auth0- servers and are not saved to our db. i'll look into it tonyte and try to remove the option.

**Comment by josedigital** [comment]
username/pw option disabled.
